export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';

// BLOG ACTIONS
export const SET_BLOGS = 'SET_BLOGS';
export const FETCH_BLOG_ID = 'FETCH_BLOG_ID';

// REQUESTS ACTIONS
export const CHANGE_SELECTED_REQUEST_TYPE = 'CHANGE_SELECTED_REQUEST_TYPE';
export const SET_REQUESTS = 'SET_REQUESTS';

// HEADER
export const UPDATE_HEADER = 'UPDATE_HEADER';