export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';

// BLOG ACTIONS
export const SET_BLOGS = 'SET_BLOGS';
export const FETCH_BLOG_ID = 'FETCH_BLOG_ID';

// HEADER
export const UPDATE_HEADER = 'UPDATE_HEADER';